### ISSUE TITLE
convert-signal-inputs fails

### ISSUE THREAD

**Issue by grosch-intl** [nartc/ngxtension-platform#290]
I have this as the last line of my component's class:

```typescript
#isPromiseBoolean = (value: unknown): value is Promise<boolean> => value instanceof Promise
```

When I run your generator, it fails with this:

<pre>
-- Details --
Path: /src/app/button-enabled-dialog/button-enabled-dialog.component.ts
Text: "...ble\n\n    #isPromiseBoolean = (value: unknown): value is Promise<boolean> => value instanceof Promise\n;\n}\n"
Stack: Error: Cannot get the next when at the end of the iterator.
    at AdvancedIterator.next (C:...\node_modules\ts-morph\dist\ts-morph.js:40:19)
    at DefaultParentHandler.handleNode (C:...\node_modules\ts-morph\dist\ts-morph.js:1542:116)
    at ParentFinderReplacementNodeHandler.handleNode (C:...\node_modules\ts-morph\dist\ts-morph.js:1615:37)
    at NodeHandlerHelper.handleForValues (C:...\node_modules\ts-morph\dist\ts-morph.js:1402:21)
    at #handleChildren (C:...\node_modules\ts-morph\dist\ts-morph.js:1471:25)
    at ParentFinderReplacementNodeHandler.handleNode (C:...\node_modules\ts-morph\dist\ts-morph.js:1461:33)
    at ParentFinderReplacementNodeHandler.handleNode (C:...\node_modules\ts-morph\dist\ts-morph.js:1618:19)
    at NodeHandlerHelper.handleForValues (C:...\node_modules\ts-morph\dist\ts-morph.js:1402:21)
    at #handleChildren (C:...\node_modules\ts-morph\dist\ts-morph.js:1471:25)
    at ParentFinderReplacementNodeHandler.handleNode (C:...\node_modules\ts-morph\dist\ts-morph.js:1461:33)
error Command failed with exit code 1.
</pre>

**Comment by joshuamorony** [comment]
Thanks @grosch-intl - the issue is that this line is not terminated with a semicolon, which is valid JS/TS syntax because of automatic semicolon insertion, but this messes with the processing we are doing in ts-morph

**Comment by grosch-intl** [comment]
Yah, I hate semicolons as they just don't add any value :)  Looking forward to your fix.

Are you planning a generator to handle viewChild, contentChild and the other new ones?

**Comment by joshuamorony** [comment]
To be clear the PR won't "fix" this in the sense that it will allow not having semi-colons, it will just warn that it has failed for this reason. I don't think it's feasible to have ts-morph support this, though I could be wrong about that.

And I'm not aware of any current plans for building a viewChild schematic, though it's probably feasible

**Comment by jefbarn** [comment]
FYI for anyone finding this in the future. An easy workaround for those using prettier is just set { semi: true } in your prettier config first, then run the migration, rerun prettier with { semi: false }.
